[package]
name = "fdmv-edit"
description = "Editing model, preview sources and export pipeline for FDMV"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
libfdmv.workspace = true
fdmv-gui.workspace = true
anyhow = "1"
dirs = "7"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tempfile = "3"
