[workspace]
resolver = "3"
members = [
    "crates/libfdmv",
    "crates/fdmv-cli",
    "crates/fdmv-gui",
    "crates/fdmv-player",
    "crates/fdmv-edit",
    "crates/fdmv-editor",
    "crates/fdmv-capture",
    "crates/fdmv-recorder",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
rust-version = "1.85"

[workspace.dependencies]
libfdmv = { path = "crates/libfdmv" }
fdmv-gui = { path = "crates/fdmv-gui" }
fdmv-edit = { path = "crates/fdmv-edit" }
fdmv-capture = { path = "crates/fdmv-capture" }
