[package]
name = "fdmv-gui"
description = "Shared GUI components (audio/video output, fonts) for FDMV apps"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
libfdmv.workspace = true
anyhow = "1"
cpal = "0.18"
eframe = "0.36"
fontdb = "0.24"
